# Docs for the Azure Web Apps Deploy action: https://github.com
# More GitHub Actions for Azure: https://github.com

name: Build and deploy ASP.Net Core app to Azure Web App - sdbp031-salman-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build SDBP031Addendum.slnx --configuration Release

      - name: dotnet publish
        run: dotnet publish SDBP031Addendum.slnx -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9EAA4E9100E64ADD928E71FC49FE94DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D0C63C9636F441D1A03CA58A89D340BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EDA65BB8C4F9436F9E42F8787D95E273 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sdbp031-salman-api' 
          package: .
